# Site settings
title: littlemountainman blog
email: 
description: "student, nomadic researcher in machine learning"
baseurl: ""
url: "http://littlemountainman.github.io"
twitter_username: littlemtman
github_username:  littlemountainman

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
